definitions:
  errs.ErrResponse:
    properties:
      error:
        type: string
    type: object
  handlers.JWT:
    properties:
      token:
        type: string
    type: object
  response.Response:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  role.Role:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - name
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      description: Provide email and password to login, response is JWT
      parameters:
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.JWT'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ErrResponse'
        "401":
          description: Unauthorizes
          schema:
            $ref: '#/definitions/errs.ErrResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/errs.ErrResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/errs.ErrResponse'
      summary: Login endpoint
  /roles:
    get:
      consumes:
      - application/json
      description: returns all roles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/role.Role'
            type: array
        "401":
          description: ""
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/errs.ErrResponse'
      security:
      - bearerAuth: []
      summary: read roles endpoint
    post:
      description: Provide role name to create new role
      parameters:
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/role.Role'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/errs.ErrResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/errs.ErrResponse'
      summary: Create role endpoint
  /roles/{id}:
    delete:
      consumes:
      - application/json
      description: provide role id to delete the role
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/errs.ErrResponse'
        "401":
          description: ""
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/errs.ErrResponse'
      security:
      - bearerAuth: []
      summary: delete a role endpoint
  /signup:
    post:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Some ID
        in: path
        name: some_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: ok
          schema:
            type: string
        "404":
          description: ok
          schema:
            type: string
      summary: Add a new pet to the store
securityDefinitions:
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
